<?php

    $genericons['Post formats'] = array('standard' => 'standard','aside' => 'aside','image' => 'image','gallery' => 'gallery','video' => 'video','status' => 'status','quote' => 'quote','link' => 'link','chat' => 'chat','audio' => 'audio');

	$genericons['Social icons'] = array('github' => 'github','dribbble' => 'dribbble','twitter' => 'twitter','facebook' => 'facebook','facebook-alt' => 'facebook-alt','wordpress' => 'wordpress','googleplus' => 'googleplus','linkedin' => 'linkedin','linkedin-alt' => 'linkedin-alt','pinterest' => 'pinterest','pinterest-alt' => 'pinterest-alt','flickr' => 'flickr','vimeo' => 'vimeo','youtube' => 'youtube','tumblr' => 'tumblr','instagram' => 'instagram','codepen' => 'codepen','polldaddy' => 'polldaddy','googleplus-alt' => 'googleplus-alt','path' => 'path','skype' => 'skype','digg' => 'digg','reddit' => 'reddit','stumbleupon' => 'stumbleupon','pocket' => 'pocket','dropbox' => 'dropbox');

	$genericons['Meta icons'] = array('comment' => 'comment','category' => 'category','tag' => 'tag','time' => 'time','user' => 'user','day' => 'day','week' => 'week','month' => 'month','pinned' => 'pinned');

	$genericons['Other icons'] = array('search' => 'search','unzoom' => 'unzoom','zoom' => 'zoom','show' => 'show','hide' => 'hide','close' => 'close','close-alt' => 'close-alt','trash' => 'trash','star' => 'star','home' => 'home','mail' => 'mail','edit' => 'edit','reply' => 'reply','feed' => 'feed','warning' => 'warning','share' => 'share','attachment' => 'attachment','location' => 'location','checkmark' => 'checkmark','menu' => 'menu','refresh' => 'refresh','minimize' => 'minimize','maximize' => 'maximize','404' => '404','spam' => 'spam','summary' => 'summary','cloud' => 'cloud','key' => 'key','dot' => 'dot','next' => 'next','previous' => 'previous','expand' => 'expand','collapse' => 'collapse','dropdown' => 'dropdown','dropdown-left' => 'dropdown-left','top' => 'top','draggable' => 'draggable','phone' => 'phone','send-to-phone' => 'send-to-phone','plugin' => 'plugin','cloud-download' => 'cloud-download','cloud-upload' => 'cloud-upload','external' => 'external','document' => 'document','book' => 'book','cog' => 'cog','unapprove' => 'unapprove','cart' => 'cart','pause' => 'pause','stop' => 'stop','skip-back' => 'skip-back','skip-ahead' => 'skip-ahead','play' => 'play','tablet' => 'tablet','send-to-tablet' => 'send-to-tablet','info' => 'info','notice' => 'notice','help' => 'help','fastforward' => 'fastforward','rewind' => 'rewind','portfolio' => 'portfolio','heart' => 'heart','code' => 'code','subscribe' => 'subscribe','unsubscribe' => 'unsubscribe','subscribed' => 'subscribed','reply-alt' => 'reply-alt','reply-single' => 'reply-single','flag' => 'flag','print' => 'print','lock' => 'lock','bold' => 'bold','italic' => 'italic','picture' => 'picture','fullscreen' => 'fullscreen');

	$genericons['Generic shapes'] = array('uparrow' => 'uparrow','rightarrow' => 'rightarrow','downarrow' => 'downarrow','leftarrow' => 'leftarrow');
